server:
  port: 8080
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
db:
  url: "jdbc:postgresql://postgres:5432/appdb?encoding=UTF8"
  schema: shop
  user: postgres
  password: postgres
  maxPoolSize: 4
kafka:
  bootstrap-servers: "kafka:9092"
  pay-response:
    topic: 'pay_response'
    delayOnErrorMillis: 1_000
    pollIntervalMillis: 1_000
    consumer:
      "[bootstrap.servers]": ${kafka.bootstrap-servers}
      "[client.id]": 'order-service-${server.port}'
      "[group.id]": 'order-service'
      "[max.pool.size]": 2
  pay-request:
    topic: 'pay_request'
    producer:
      "[bootstrap.servers]": ${kafka.bootstrap-servers}
      "[client.id]": 'order-service-${server.port}'
  order-push:
    topic: 'order_push'
    producer:
      "[bootstrap.servers]": ${kafka.bootstrap-servers}
      "[client.id]": 'order-service-${server.port}'