server:
  # tcp-ip порт, на котором будет доступен web-сервер
  port: 8080
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
management:
  endpoint:
    health:
      enabled: true
      show-details: always
  endpoints:
    web:
      exposure:
        include: health
db:
  url: "jdbc:postgresql://postgres:5432/appdb?encoding=UTF8"
  schema: shop
  user: postgres
  password: postgres
  maxPoolSize: 4
kafka:
  bootstrap-servers: "kafka:9092"
  request:
    topic: 'pay_request'
    delayOnErrorMillis: 1_000
    pollIntervalMillis: 1_000
    consumer:
      "[bootstrap.servers]": "${kafka.bootstrap-servers}"
      "[client.id]": 'payment-service-${server.port}'
      "[group.id]": 'payment-service'
      "[max.pool.size]": 2
  response:
    topic: 'pay_response'
    producer:
      "[bootstrap.servers]": "${kafka.bootstrap-servers}"
      "[client.id]": 'payment-service-${server.port}'