server:
  port: 8080
router:
  order-service:
    endpoints:
      - 'http://order-service:8080'
  payment-service:
    endpoints:
      - 'http://payment-service:8080'
kafka:
  order-push:
    topic: 'order_push'
    delayOnErrorMillis: 1_000
    pollIntervalMillis: 1_000
    consumer:
      "[bootstrap.servers]": "kafka:9092"
      "[client.id]": 'gateway-service'
      "[group.id]": 'gateway-service'
      "[max.pool.size]": 2